name: Daily Cron
on:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Run Cronjobs
        run: |
          curl --request POST \
          --url https://admin-server-lxrpo86fe-radium-rocket.vercel.app/cron \
          --header 'Authorization:${{ secrets.API_SECRET_KEY }}'
