name: Daily Cron
on:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Run Cronjobs
        run: |
          curl --request POST \
          --url ${{ secrets.ENV_URL}}/cron \
          --header 'Authorization:${{ secrets.API_SECRET_KEY }}'
